# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: 127.0.0.1 (MySQL 5.5.29)
# Database: spacecraft
# Generation Time: 2017-03-11 04:11:04 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table feed_contents
# ------------------------------------------------------------

DROP TABLE IF EXISTS `feed_contents`;

CREATE TABLE `feed_contents` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `feed_id` int(11) unsigned DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `permalink` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `feed_id` (`feed_id`),
  CONSTRAINT `feed_id` FOREIGN KEY (`feed_id`) REFERENCES `feeds` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `feed_contents` WRITE;
/*!40000 ALTER TABLE `feed_contents` DISABLE KEYS */;

INSERT INTO `feed_contents` (`id`, `feed_id`, `title`, `description`, `permalink`)
VALUES
	(1,1,'PHP 5.5.21 is released','The PHP development team announces the immediate availability of PHP 5.5.21. This release fixes several bugs as well as CVE-2015-0231, CVE-2014-9427 and CVE-2015-0232. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.21 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in th...','http://php.net/index.php#id2015-01-22-1'),
	(2,1,'PHP 5.6.5 is available','The PHP development team announces the immediate availability of PHP 5.6.5. This release fixes several bugs as well as CVE-2015-0231, CVE-2014-9427 and CVE-2015-0232. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.5 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ...','http://php.net/index.php#id2015-01-22-2'),
	(3,1,'PHP 5.4.37 Released','The PHP development team announces the immediate availability of PHP 5.4.37. Six security-related bugs were fixed in this release, including CVE-2015-0231, CVE-2014-9427 and CVE-2015-0232. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.37 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of chan...','http://php.net/index.php#id2015-01-22-3'),
	(4,1,'PHP 5.4.38 Released','The PHP development team announces the immediate availability of PHP 5.4.38. Seven security-related bugs were fixed in this release, including CVE-2015-0273 and mitigation for CVE-2015-0235. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.38 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of ch...','http://php.net/index.php#id2015-02-18-1'),
	(5,1,'PHP 5.5.22 is available','The PHP development team announces the immediate availability of PHP 5.5.22. This release fixes several bugs and addresses CVE-2015-0235 and CVE-2015-0273. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.22 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-02-19-1'),
	(6,1,'PHP 5.6.6 is available','The PHP development team announces the immediate availability of PHP 5.6.6. This release fixes several bugs and addresses CVE-2015-0235 and CVE-2015-0273. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.6 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-02-19-2'),
	(7,1,'PHP 5.4.39 Released','The PHP development team announces the immediate availability of PHP 5.4.39. Six security-related bugs were fixed in this release, including CVE-2015-0231, CVE-2015-2305 and CVE-2015-2331. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.39 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of chan...','http://php.net/index.php#id2015-03-19-2'),
	(8,1,'PHP 5.5.23 is available','The PHP development team announces the immediate availability of PHP 5.5.23. Several bugs have been fixed as well as CVE-2015-0231, CVE-2015-2305 and CVE-2015-2331. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.23 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the C...','http://php.net/index.php#id2015-03-20-1'),
	(9,1,'PHP 5.6.7 is available','The PHP development team announces the immediate availability of PHP 5.6.7. Several bugs have been fixed as well as CVE-2015-0231, CVE-2015-2305 and CVE-2015-2331. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.7 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the Cha...','http://php.net/index.php#id2015-03-20-2'),
	(10,1,'PHP 5.5.24 is available','The PHP development team announces the immediate availability of PHP 5.5.24. Several bugs have been fixed some of them beeing security related, like CVE-2015-1351 and CVE-2015-1352. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.24 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is ...','http://php.net/index.php#id2015-04-16-1'),
	(11,1,'PHP 5.6.8 is available','The PHP development team announces the immediate availability of PHP 5.6.8. Several bugs have been fixed some of them beeing security related, like CVE-2015-1351 and CVE-2015-1352. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.8 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is re...','http://php.net/index.php#id2015-04-16-2'),
	(12,1,'PHP 5.4.40 Released','The PHP development team announces the immediate availability of PHP 5.4.40. 14 security-related bugs were fixed in this release, including CVE-2014-9709, CVE-2015-2301, CVE-2015-2783, CVE-2015-1352. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.40 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The l...','http://php.net/index.php#id2015-04-16-3'),
	(13,1,'PHP 5.5.25 is available','The PHP development team announces the immediate availability of PHP 5.5.25. Several bugs have been fixed. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.25 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-05-14-1'),
	(14,1,'PHP 5.4.41 Released','The PHP development team announces the immediate availability of PHP 5.4.41. Seven security-related issues were fixed in this version. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.41 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-05-14-2'),
	(15,1,'PHP 5.6.9 is available','The PHP development team announces the immediate availability of PHP 5.6.9. Several bugs have been fixed. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.9 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-05-14-3'),
	(16,1,'PHP 5.5.26 is available','The PHP development team announces the immediate availability of PHP 5.5.26. Several bugs have been fixed as well as several security issues into some bundled libraries (CVE-2015-3414, CVE-2015-3415, CVE-2015-3416, CVE-2015-2325 and CVE-2015-2326). All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.26 please visit our downloads page, Windows binaries...','http://php.net/index.php#id2015-06-11-1'),
	(17,1,'PHP 5.6.10 is available','The PHP development team announces the immediate availability of PHP 5.6.10. Several bugs have been fixed as well as several security issues into some bundled libraries (CVE-2015-3414, CVE-2015-3415, CVE-2015-3416, CVE-2015-2325 and CVE-2015-2326). All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.10 please visit our downloads page, Windows binaries...','http://php.net/index.php#id2015-06-11-2'),
	(18,1,'PHP 5.4.42 Released','The PHP development team announces the immediate availability of PHP 5.4.42. Six security-related issues in PHP were fixed in this release, as well as several security issues in bundled sqlite library (CVE-2015-3414, CVE-2015-3415, CVE-2015-3416). All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.42 please visit our downloads page, Windows binaries ...','http://php.net/index.php#id2015-06-11-4'),
	(19,1,'PHP 5.4.43 Released','The PHP development team announces the immediate availability of PHP 5.4.43. Five security-related issues in PHP were fixed in this release, including CVE-2015-3152. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.43 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ...','http://php.net/index.php#id2015-07-09-1'),
	(20,1,'PHP 5.5.27 released','The PHP development team announces the immediate availability of PHP 5.5.27. Several bugs were fixed in this release as well as CVE-2015-3152. All PHP 5.5 users are encouraged to upgrade to this version. According to our release calendar, this PHP 5.5 version is the last planned release that contains regular bugfixes. All the consequent releases will contain only security-relevant fixes, for...','http://php.net/index.php#id2015-07-10-2'),
	(21,1,'PHP 5.6.11 is available','The PHP development team announces the immediate availability of PHP 5.6.11. Five security-related issues in PHP were fixed in this release, including CVE-2015-3152. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.11 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ...','http://php.net/index.php#id2015-07-10-3'),
	(22,1,'PHP 5.4.44 Released','The PHP development team announces the immediate availability of PHP 5.4.44. 11 security-related issues were fixed in this release. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.44 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog. Please note that PHP 5....','http://php.net/index.php#id2015-08-06-2'),
	(23,1,'PHP 5.5.28 Released','The PHP development team announces the immediate availability of PHP 5.5.28. 12 security-related issues were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. According to our release calendar, this PHP 5.5 version is the first security release of the PHP 5.5 branch. This and all the following releases of this branch do not contain bugfixes that are not cons...','http://php.net/index.php#id2015-08-06-3'),
	(24,1,'PHP 5.6.12 is available','The PHP development team announces the immediate availability of PHP 5.6.12. 12 security-related issues were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.12 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-08-06-4'),
	(25,1,'PHP 5.6.13 is available','The PHP development team announces the immediate availability of PHP 5.6.13. 11 security-related issues were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.13 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-09-04-2'),
	(26,1,'PHP 5.5.29 is available','The PHP development team announces the immediate availability of PHP 5.5.29. This is a security release. Many security-related issues were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.29 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the Chan...','http://php.net/index.php#id2015-09-04-3'),
	(27,1,'PHP 5.4.45 Released','The PHP development team announces the immediate availability of PHP 5.4.45. Ten security-related issues were fixed in this release. All PHP 5.4 users are encouraged to upgrade to this version. For source downloads of PHP 5.4.45 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog. Please note that accor...','http://php.net/index.php#id2015-09-04-4'),
	(28,1,'PHP 5.5.30 is available','The PHP development team announces the immediate availability of PHP 5.5.30. This is a security release. Two security bugs were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.30 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-10-01-2'),
	(29,1,'PHP 5.6.14 is available','The PHP development team announces the immediate availability of PHP 5.6.14. This is a security release. Two security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.14 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-10-01-3'),
	(30,1,'PHP 5.6.15 is available','The PHP development team announces the immediate availability of PHP 5.6.15. Several bugs have been fixed. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.15 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-10-29-2'),
	(31,1,'PHP 5.6.16 is available','The PHP development team announces the immediate availability of PHP 5.6.16. Several bugs have been fixed. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.16 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2015-11-26-2'),
	(32,1,'PHP 5.5.31 is available','The PHP development team announces the immediate availability of PHP 5.5.31. This is a security release. Several security bugs were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.31 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-01-07-2'),
	(33,1,'PHP 5.6.17 is available','The PHP development team announces the immediate availability of PHP 5.6.17. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.17 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-01-07-3'),
	(34,1,'PHP 5.5.32 is available','The PHP development team announces the immediate availability of PHP 5.5.32. This is a security release. Several security bugs were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.32 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-02-04-2'),
	(35,1,'PHP 5.6.18 is available','The PHP development team announces the immediate availability of PHP 5.6.18. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.18 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-02-04-3'),
	(36,1,'PHP 5.5.33 is available','The PHP development team announces the immediate availability of PHP 5.5.33. This is a security release in which two security bugs were fixed. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.33 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-03-03-2'),
	(37,1,'PHP 5.6.19 is available','The PHP development team announces the immediate availability of PHP 5.6.19. This is a security release in which several security bugs were fixed. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.19 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-03-03-3'),
	(38,1,'PHP 5.5.34 is available','The PHP development team announces the immediate availability of PHP 5.5.34. This is a security release. Several security bugs were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.34 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-03-31-2'),
	(39,1,'PHP 5.6.20 is available','The PHP development team announces the immediate availability of PHP 5.6.20. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.20 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-03-31-4'),
	(40,1,'PHP 5.5.35 Release','The PHP development team announces the immediate availability of PHP 5.5.35. This is a security release. Several security bugs were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.35 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-04-28-1'),
	(41,1,'PHP 5.6.21 is available','The PHP development team announces the immediate availability of PHP 5.6.21. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.21 please visit our downloads page, Windows binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-04-28-2'),
	(42,1,'PHP 5.5.36 is available','The PHP development team announces the immediate availability of PHP 5.5.36. This is a security release. Several security bugs were fixed in this release. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.36 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the ...','http://php.net/index.php#id2016-05-26-2'),
	(43,1,'PHP 5.6.22 is available','The PHP development team announces the immediate availability of PHP 5.6.22. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.22 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the ...','http://php.net/index.php#id2016-05-26-3'),
	(44,1,'PHP 7.1.0 Alpha 1 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Alpha 1. This release marks the beginning of the first minor release in the PHP 7.x series. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! PHP 7.1.0 Alpha 1 comes with fea...','http://php.net/index.php#id2016-06-09-1'),
	(45,1,'PHP 5.6.23 is released','The PHP development team announces the immediate availability of PHP 5.6.23. Several bugs were fixed in this release, including security-related ones. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.23 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the Chan...','http://php.net/index.php#id2016-06-23-2'),
	(46,1,'PHP 5.5.37 is released','The PHP development team announces the immediate availability of PHP 5.5.37. This is a security release, several security bugs were fixed. All PHP 5.5 users are encouraged to upgrade to this version. For source downloads of PHP 5.5.37 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2016-06-23-3'),
	(47,1,'PHP 7.1.0 Alpha 2 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Alpha 2. This is the second alpha release for PHP 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and other changes, you can...','http://php.net/index.php#id2016-06-24-1'),
	(48,1,'PHP 7.1.0 Alpha 3 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Alpha 3. This release is the last alpha for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! PHP 7.1.0 Alpha 3 builds on previous releases with: Iterable type. HTTP/2...','http://php.net/index.php#id2016-07-07-1'),
	(49,1,'PHP 7.1.0 Beta 1 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Beta 1. This release is the first beta for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! PHP 7.1.0 Beta 1 builds on previous releases with: Asynchronous Signal Han...','http://php.net/index.php#id2016-07-21-1'),
	(50,1,'PHP 5.5.38 is released','The PHP development team announces the immediate availability of PHP 5.5.38. This is a security release that fixes some security related bugs. All PHP 5.5 users are encouraged to upgrade to this version.For source downloads of PHP 5.5.38 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download. The list of changes is recorded in the ChangeLog. Not...','http://php.net/index.php#id2016-07-21-2'),
	(51,1,'PHP 5.6.24 is released','The PHP development team announces the immediate availability of PHP 5.6.24. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. For source downloads of PHP 5.6.24 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the ...','http://php.net/index.php#id2016-07-21-4'),
	(52,1,'PHP 7.1.0 Beta 2 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Beta 2. This release is the second beta for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and other changes, you can read ...','http://php.net/index.php#id2016-08-04-1'),
	(53,1,'PHP 5.6.25 is released','The PHP development team announces the immediate availability of PHP 5.6.25. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version.For source downloads of PHP 5.6.25 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the C...','http://php.net/index.php#id2016-08-18-2'),
	(54,1,'PHP 7.1.0 Beta 3 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Beta 3. This release is the last beta for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and other changes, you can read th...','http://php.net/index.php#id2016-08-18-3'),
	(55,1,'PHP 7.1.0 Release Candidate 1 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Release Candidate 1. This release is the first release candidate for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and oth...','http://php.net/index.php#id2016-09-01-1'),
	(56,1,'PHP 5.6.26 is released','The PHP development team announces the immediate availability of PHP 5.6.26. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version.For source downloads of PHP 5.6.26 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the C...','http://php.net/index.php#id2016-09-16-1'),
	(57,1,'PHP 7.1.0 Release Candidate 2 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Release Candidate 2. This release is the second release candidate for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and ot...','http://php.net/index.php#id2016-09-16-2'),
	(58,1,'PHP 7.1.0 Release Candidate 3 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Release Candidate 3. This release is the third release candidate for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and oth...','http://php.net/index.php#id2016-09-29-1'),
	(59,1,'PHP 5.6.27 Released','The PHP development team announces the immediate availability of PHP 5.6.27. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version.For source downloads of PHP 5.6.27 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the C...','http://php.net/index.php#id2016-10-14-1'),
	(60,1,'PHP 7.1.0 Release Candidate 4 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Release Candidate 4. This release is the fourth release candidate for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and ot...','http://php.net/index.php#id2016-10-19-1'),
	(61,1,'PHP 7.1.0 Release Candidate 5 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Release Candidate 5. This release is the fifth release candidate for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new features and oth...','http://php.net/index.php#id2016-10-27-1'),
	(62,1,'PHP 7.1.0 Release Candidate 6 Released','The PHP development team announces the immediate availability of PHP 7.1.0 Release Candidate 6. This release is the sixth and final release candidate for 7.1.0. All users of PHP are encouraged to test this version carefully, and report any bugs and incompatibilities in the bug tracking system. THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION! For more information on the new featur...','http://php.net/index.php#id2016-11-10-2'),
	(63,1,'PHP 5.6.28 Released','The PHP development team announces the immediate availability of PHP 5.6.28. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version.For source downloads of PHP 5.6.28 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the C...','http://php.net/index.php#id2016-11-10-3'),
	(64,1,'PHP 7.1.0 Released','The PHP development team announces the immediate availability of PHP 7.1.0. This release is the first point release in the 7.x series.PHP 7.1.0 comes with numerous improvements and new features such asNullable typesVoid return typeIterable pseudo-typeClass constant visiblity modifiersSquare bracket syntax for list() and the ability to specify keys in list()Catching multiple exceptions typesM...','http://php.net/index.php#id2016-12-01-3'),
	(65,1,'PHP 5.6.29 Released','The PHP development team announces the immediate availability of PHP 5.6.29. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version.For source downloads of PHP 5.6.29 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the C...','http://php.net/index.php#id2016-12-08-2'),
	(66,1,'PHP 7.1.1 Released','The PHP development team announces the immediate availability of PHP 7.1.1. Several bugs have been fixed. All PHP 7.1 users are encouraged to upgrade to this version. For source downloads of PHP 7.1.1 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2017-01-19-1'),
	(67,1,'PHP 5.6.30 Released','The PHP development team announces the immediate availability of PHP 5.6.30. This is a security release. Several security bugs were fixed in this release. All PHP 5.6 users are encouraged to upgrade to this version. According to our release calendar, this PHP 5.6 version is the last planned release that contains regular bugfixes. All the consequent releases will contain only security-relevan...','http://php.net/index.php#id2017-01-19-3'),
	(68,1,'PHP 7.1.2 Released','The PHP development team announces the immediate availability of PHP 7.1.2. Several bugs have been fixed. All PHP 7.1 users are encouraged to upgrade to this version. For source downloads of PHP 7.1.2 please visit our downloads page, Windows source and binaries can be found on windows.php.net/download/. The list of changes is recorded in the ChangeLog.','http://php.net/index.php#id2017-02-17-1'),
	(69,2,'U.S. Jobs, Pay Show Solid Gains in Trump\'s First Full Month','Two anonymous reader share a Bloomberg report: U.S. employers added jobs at an above-average pace for a second month on outsized gains in construction and manufacturing while wage growth picked up, as the labor market continued its steady improvement in the new year. The 235,000 increase followed a 238,000 rise in January that was more than previously estimated, the best back-to-back rise si...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/9ihdEIo23a0/us-jobs-pay-show-solid-gains-in-trumps-first-full-month'),
	(70,2,'How Many Snapchat Clones Does It Take For Facebook To Lose Its Self-Respect?','Alex Hern, writing for The Guardian: Over the past year, Facebook has shown an almost monomaniacal dedication to taking on Snapchat by importing its defining features wholesale into the company\'s own apps. Facebook Live has \"masks\" now (think Snapchat\'s Lenses). Instagram has geostickers (like Snapchat\'s location-aware stickers.) WhatsApp has \"Status\" (think Snapchat Stories). Instagram has ...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/85tc0TBOjqY/how-many-snapchat-clones-does-it-take-for-facebook-to-lose-its-self-respect'),
	(71,2,'Africa Gets Its Own Web Address','Africa now has the unique web address .africa, equivalent to the more familiar .com, following its official launch by the African Union. From a report on BBC: AU commission chairperson Nkosazana Dlamini Zuma hailed its creation as the moment when Africa \"got [its] own digital identity.\" The AU says the .africa domain name will \"bring the continent together as an internet community.\" Addresse...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/FGMKT09qyK8/africa-gets-its-own-web-address'),
	(72,2,'Pennsylvania Sues IBM Over Jobless Claims System Upgrade','Pennsylvania has sued IBM for $170 million, claiming the company failed to deliver a promised upgrade to its outdated system of processing unemployment claims. From a report: IBM did not immediately respond to a request for comment but a company representative told the Associated Press the suit had no merit and the company would fight it. The suit stems from a 2006 fixed-price contract award...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/EAEkS-wPMOA/pennsylvania-sues-ibm-over-jobless-claims-system-upgrade'),
	(73,2,'Alphabet\'s Waymo Asks Judge To Block Uber From Using Self-Driving Car Secrets','Waymo, Alphabet\'s self-driving spinoff from Google, is formally asking a judge to block Uber from operating its autonomous vehicles, according to new documents filed in Waymo\'s lawsuit against Uber. From a report on The Verge: The lawsuit, which was filed last month, alleges that Uber stole key elements of its self-driving car technology from Google. Uber has called the accusations \"baseless...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/Xfv1Kl2Ja0Q/alphabets-waymo-asks-judge-to-block-uber-from-using-self-driving-car-secrets'),
	(74,2,'Microsoft Admits Mistake, Pulls Problematic Windows 10 Driver','Wayne Williams, writing for BetaNews: Microsoft pushed out a mysterious driver to Windows users on Wednesday that caused big problems for some. The driver, listed as \"Microsoft -- WPD -- 2/22/2016 12:00:00 AM -- 5.2.5326.4762,\" wasn\'t accompanied by any details, although we knew from the name that it related to Windows Portable Devices and affected users who had phones and tablets connected ...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/Ws2H5a3hr9M/microsoft-admits-mistake-pulls-problematic-windows-10-driver'),
	(75,2,'Oculus CTO John Carmack Is Suing ZeniMax For $22.5 Million','An anonymous reader quotes a report from TechCrunch: The feud between Oculus and ZeniMax Media is opening up once again, this time with the CTO of Oculus, John Carmack, suing his former employer for earnings that he claims are still owed to him. The suit is largely unrelated to the $6 billion trade secrets suit which ended last month with a $500 million judgment against Oculus. Instead, Carm...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/q6YHDqE06Qs/oculus-cto-john-carmack-is-suing-zenimax-for-225-million'),
	(76,2,'The SEC Just Handed Bitcoin a Huge Setback','The SEC has decided to deny an application for the first exchange-traded product that tracks the price of bitcoin, according to an order posted on the regulator\'s website. From a report: In an order today, the commission found that the proposed fund was too susceptible to fraud, due to the unregulated nature of Bitcoin. The result is a major setback for the fund, and a frustrating false star...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/raQcJZJuj9M/the-sec-just-handed-bitcoin-a-huge-setback'),
	(77,2,'Blogger Wins Libel Damages Over Columnist\'s Tweets','eionmac shares a report that details a legal battle in which a food blogger won thousands of dollars in libel damages \"after a row over two tweets.\" BBC reports: Food blogger Jack Monroe has won 24,000 British pounds damages, plus legal costs, in a libel action against columnist Katie Hopkins after a row over two tweets. Ms Monroe sued the writer over two war memorial tweets she said caused ...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/T3x2cRHyRgs/blogger-wins-libel-damages-over-columnists-tweets'),
	(78,2,'Message For AMD: Open PSP Will Improve Security, Hinder Intel','futuristicrabbit writes: AMD has faced calls from Edward Snowden, Libreboot and the Reddit community to release the source code to the AMD Secure Processor (PSP), a network-capable co-processor which some believe has the capacity to act as a backdoor. Opening the PSP would not only have security benefits, but would provide AMD with a competitive advantage against rival chipmaker Intel. Lisa ...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/__tXE03JwNE/message-for-amd-open-psp-will-improve-security-hinder-intel'),
	(79,2,'MAC Address Randomization Flaws Leave Android and iOS Phones Open To Tracking','New submitter cryptizard writes: Modern Android and iOS versions include a technology called MAC address randomization to prevent passive tracking of users as they move from location to location. Unfortunately, researchers have revealed that this technology is implemented sporadically by device manufacturers and is often deployed with significant flaws that allow it to be easily defeated. A ...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/yqPPDRW_ArE/mac-address-randomization-flaws-leave-android-and-ios-phones-open-to-tracking'),
	(80,2,'Intel Security Releases Detection Tool For EFI Rootkits After CIA Leak','After WikiLeaks revealed data exposing information about the CIA\'s arsenal of hacking tools, Intel Security has released a tool that allows users to check if their computer\'s low-level system firmware has been modified and contains unauthorized code. PCWorld reports: The release comes after CIA documents leaked Tuesday revealed that the agency has developed EFI (Extensible Firmware Interface...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/QBXouQA4FdE/intel-security-releases-detection-tool-for-efi-rootkits-after-cia-leak'),
	(81,2,'3D-Printed House Constructed On-Site In One Day','Heffenfeffer writes: Russian company Apis Cor has manufactured a 3D printed concrete house on-site in 24 hours in Stupino Town, Russia. Using a tower crane-shaped concrete extruder that can rotate 360 degrees, the 38 square meter (408.88 square foot) rotor-shaped home walls were constructed in one day. Voids left in the manufacturing process were filled by hand, installing windows, doors, an...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/5tz_GhmrvfU/3d-printed-house-constructed-on-site-in-one-day'),
	(82,2,'Scientists Create \'Designer Yeast\' In Major Step Toward Synthetic Life','An anonymous reader quotes a report from Washington Post: In a significant advance toward creating the first \"designer\" complex cell, scientists say they are one-third of the way to synthesizing the complete genome of baker\'s yeast. In seven studies published Thursday in the journal Science, the researchers describe how they built six of the 16 chromosomes required for the yeast Saccharomyce...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/rMVnKdGOfbE/scientists-create-designer-yeast-in-major-step-toward-synthetic-life'),
	(83,2,'New Bill Would Allow Employers To Demand Genetic Testing From Workers','capedgirardeau quotes a report from Business Insider: A little-noticed bill moving through the U.S. Congress would allow companies to require employees to undergo genetic testing or risk paying a penalty of thousands of dollars, and would let employers see that genetic and other health information. Giving employers such power is now prohibited by U.S. law, including the 2008 genetic privacy ...','http://rss.slashdot.org/~r/Slashdot/slashdot/~3/02rgZgKytyg/new-bill-would-allow-employers-to-demand-genetic-testing-from-workers');

/*!40000 ALTER TABLE `feed_contents` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table feeds
# ------------------------------------------------------------

DROP TABLE IF EXISTS `feeds`;

CREATE TABLE `feeds` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `last_updated` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `feeds` WRITE;
/*!40000 ALTER TABLE `feeds` DISABLE KEYS */;

INSERT INTO `feeds` (`id`, `title`, `url`, `last_updated`)
VALUES
	(1,'PHP: Hypertext Preprocessor','http://www.php.net/news.rss','2017-03-11 03:55:05'),
	(2,'Slashdot','http://slashdot.org/rss/slashdot.rss','2017-03-11 04:06:15');

/*!40000 ALTER TABLE `feeds` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
